#!/usr/bin/env bash
#installing the ufw firewall

sudo apt install ufw

#configure it to block all incoming traffic except the tcp ports 22, 443, and 80.

sudo ufw default deny incoming
sudo ufw default deny outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
