#!/usr/bin/env bash
# Load balancer installations

#Get update and upgrade
sudo apt-get -y update
sudo apt-get -y upgrade

#Install haproxy
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\\listen 5762-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 5695-web-02 34.224.174.8:80 check\n\tserver 5695-web-01 54.234.246.98:80 check" /etc/haproxy/haproxy.cfg

#test and restart
sudo haproxy -t
sudo service haproxy start
