#!/usr/bin/env bash
# to install nginx on a remote server 
sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
