#!/usr/bin/env bash
# install nginx on remote server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Holberton School" | sudo tee /var/www/html/index.html
sudo ngix -t 
sudo service nginx start
